2020-08-26T08:18:13.5483787+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T08:18:13.5529745+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T08:18:13.5549169+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T08:18:13.5563783+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T08:18:13.5578712+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T08:20:36.8507912+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T08:20:36.8551901+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T08:20:36.8568383+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T08:20:36.8581953+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T08:20:36.8595190+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T08:20:52.0876696+03:00 0HM29FV20MSTM:00000013 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: Unable to resolve service for type 'NetMap.Data.Repositories.Interfaces.IUserRepository' while attempting to activate 'NetMap.Web.Controllers.AccountController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-26T08:22:38.2044884+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T08:22:38.2084641+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T08:22:38.2101153+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T08:22:38.2117819+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T08:22:38.2135713+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T08:24:08.3497865+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T08:24:08.3540814+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T08:24:08.3555360+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T08:24:08.3568256+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T08:24:08.3580058+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T08:24:21.5888799+03:00 0HM29G112Q8SL:00000013 [INF] Created user: yosa, yosaa5782@gmail.com (a54048d9)
2020-08-26T08:24:27.5999771+03:00 0HM29G112Q8SL:00000017 [INF] user: yosaa5782@gmail.com has been authenticated (803ff92f)
2020-08-26T08:24:27.7314653+03:00 0HM29G112Q8SL:00000017 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ArgumentNullException: Value cannot be null. (Parameter 'principal')
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
   at NetMap.Web.Controllers.AccountController.Login(String email, String password) in D:\asp.net apps\NetMap\NetMap.Web\Controllers\AccountController.cs:line 50
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-26T21:13:51.0041327+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T21:13:51.0082640+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T21:13:51.0098780+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T21:13:51.0112725+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T21:13:51.0127996+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T21:14:35.6019820+03:00 0HM29TF4GDHRJ:00000027 [INF] Created user: yosa, yosa12978@gmail.com (2b626634)
2020-08-26T21:14:37.8699502+03:00 0HM29TF4GDHRJ:00000027 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
MailKit.Security.AuthenticationException: 535: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 10sm661801ljn.22 - gsmtp
 ---> MailKit.Net.Smtp.SmtpCommandException: 5.7.8 Username and Password not accepted. Learn more at
5.7.8  https://support.google.com/mail/?p=BadCredentials 10sm661801ljn.22 - gsmtp
   --- End of inner exception stack trace ---
   at MailKit.Net.Smtp.SmtpClient.AuthenticateAsync(Encoding encoding, ICredentials credentials, Boolean doAsync, CancellationToken cancellationToken)
   at NetMap.Data.Repositories.Mocks.EmailRepository.SendEmailAsync(String email, String subject, String message) in D:\asp.net apps\NetMap\NetMap.Data\Repositories\Mocks\EmailRepository.cs:line 35
   at NetMap.Web.Controllers.AccountController.Signup(String username, String email, String password, String passwordC) in D:\asp.net apps\NetMap\NetMap.Web\Controllers\AccountController.cs:line 112
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-26T21:17:32.0979335+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T21:17:32.1020533+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T21:17:32.1035886+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T21:17:32.1048343+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T21:17:32.1060658+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T21:17:48.0268121+03:00 0HM29TH6F18RC:00000015 [INF] Created user: yosa, yosa12978@gmail.com (2b626634)
2020-08-26T21:17:50.4068767+03:00 0HM29TH6F18RC:00000017 [ERR] The view '"Confrim"' was not found. Searched locations: ["/Views/Account/Confrim.cshtml", "/Views/Shared/Confrim.cshtml"] (9bb2756c)
2020-08-26T21:17:50.4443514+03:00 0HM29TH6F18RC:00000017 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: The view 'Confrim' was not found. The following locations were searched:
/Views/Account/Confrim.cshtml
/Views/Shared/Confrim.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-26T21:18:13.4688636+03:00 0HM29TH6F18RC:0000001D [INF] user: yosa12978@gmail.com has been authenticated (6cebe7d9)
2020-08-26T21:19:37.2033486+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T21:19:37.2072906+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T21:19:37.2086919+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T21:19:37.2099376+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T21:19:37.2114396+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T21:19:44.4658006+03:00 0HM29TIBOO50V:00000013 [INF] user: yosa12978@gmail.com has been authenticated (6cebe7d9)
2020-08-26T21:20:30.2494308+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T21:20:30.2544789+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T21:20:30.2560261+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T21:20:30.2573318+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T21:20:30.2586872+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T21:20:46.9939155+03:00 0HM29TIRGGQON:00000015 [INF] user: yosa12978@gmail.com has been authenticated (6cebe7d9)
2020-08-26T21:21:26.7808032+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T21:21:26.7846849+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T21:21:26.7866037+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T21:21:26.7883078+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T21:21:26.7897152+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T21:21:34.4717854+03:00 0HM29TJCE00QQ:00000013 [INF] user: yosa12978@gmail.com has been authenticated (6cebe7d9)
2020-08-26T21:21:34.6162670+03:00 0HM29TJCE00QQ:00000013 [ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.InvalidOperationException: No authenticationScheme was specified, and there was no DefaultSignInScheme found. The default schemes can be set using either AddAuthentication(string defaultScheme) or AddAuthentication(Action<AuthenticationOptions> configureOptions).
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
   at NetMap.Web.Controllers.AccountController.Login(String email, String password) in D:\asp.net apps\NetMap\NetMap.Web\Controllers\AccountController.cs:line 76
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-08-26T21:23:16.3376916+03:00  [INF] Now listening on: "https://localhost:5001" (d826f4b8)
2020-08-26T21:23:16.3611294+03:00  [INF] Now listening on: "http://localhost:5000" (d826f4b8)
2020-08-26T21:23:16.3628274+03:00  [INF] Application started. Press Ctrl+C to shut down. (dcaefe54)
2020-08-26T21:23:16.3640557+03:00  [INF] Hosting environment: "Development" (c3307c92)
2020-08-26T21:23:16.3653011+03:00  [INF] Content root path: "D:\asp.net apps\NetMap\NetMap.Web" (b5d60022)
2020-08-26T21:23:23.6288347+03:00 0HM29TKD216NR:00000013 [INF] user: yosa12978@gmail.com has been authenticated (6cebe7d9)
2020-08-26T21:23:26.2066580+03:00 0HM29TKD216NR:00000017 [INF] User yosa has been logged out (6c9caa3e)
